---
# tasks file for tomcat
    - name: create a custom fact directory
      file:
        path: /etc/ansible/facts.d
        state: directory
    - name: insert custom fact file
      copy:
        src: files/custom.fact
        dest: /etc/ansible/facts.d/custom.fact
    - name: Downloading required tomcat
      debug: var=tomcat_url
    - name: update the repo
      yum:
        name: "*"
        state: latest
    - name: we will install java
      yum:
        name: "{{ req_java }}"
        state: present
    - name: set default path for your java
      alternatives:
        name: java
        link: /usr/bin/java
        path: /usr/lib/jvm/{{set_java}}/bin/java
    - name: Download required tomcat
      get_url:
        url: "{{ tomcat_url }}"
        dest: /usr/local
    - name: extract download the tomcat
      unarchive:
        src: "/usr/local/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
        dest: /usr/local
        remote_src: yes
    - name: delete existing directory
      file:
       path: /usr/local/latest/apache-tomcat-{{req_tomcat_ver}}
       state: absent
    - name: rename the tomcat home directory
      command: mv /usr/local/apache-tomcat-{{req_tomcat_ver}} /usr/local/latest
    - name: Replace the default port with required port
      template:
        src: server.xml.j2
        dest: /usr/local/latest/conf/server.xml
    - name: starting tomcat
      shell: nohup /usr/local/latest/bin/startup.sh &

